version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
  build:
    commands:
      - python -m pytest --junitxml=/tmp/testreport.xml

reports:
  pytest_reports:
    files:
      - testreport.xml

    base-directory: /tmp
    file-format: JUNITXML